name: Windows Server 2022

on:
  pull_request:
    types: [synchronize, opened]
  push:

env:
  OPENCV_VERSION: 4.10.0

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        platform: ["win"]
        #platform: ["win", "uwp"]
        arch: ["x86", "x64", "ARM", "arm64"]
        exclude:
          - platform: win
            arch: ARM

    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install Server-Media-Foundation
        shell: powershell
        run: |
          Install-WindowsFeature Server-Media-Foundation

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Install NASM to support SIMD optimizations 
        uses: ilammy/setup-nasm@v1

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          cd C:\vcpkg
          .\bootstrap-vcpkg.bat
  
      - name: Add vcpkg to PATH
        shell: pwsh
        run: |
          echo "::add-path::C:\vcpkg"

      - name: Vcpkg
        shell: powershell
        if: ${{ matrix.platform == 'win' }}
        run: |
          echo ${env:VCPKG_ROOT}
          & ${env:VCPKG_ROOT}\vcpkg install opencv4[contrib]:${{matrix.arch}}-windows-static
          & ${env:VCPKG_ROOT}\vcpkg integrate install
          & ${env:VCPKG_ROOT}\vcpkg list
          ls ${env:VCPKG_ROOT}\installed
          
