name: Build OpenCV + OpenCV-Contrib

on:
  push:

jobs:
  build_packages:
    runs-on: windows-latest

    steps:
      - name: Fetch code
        uses: actions/checkout@v4
        with:
          submodules: recursive
