name: Build OpenCV + OpenCV-Contrib

on:
  push:

jobs:
  build_packages:
    runs-on: windows-latest

    steps:
      - name: Fetch code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fetching specific version of submodules
        run: |
          git submodule foreach --recursive 'git checkout tags/4.11.0'
          git submodule foreach --recursive 'git pull --ff-only'
