name: Build OpenCV + OpenCV-Contrib

on:
  push:

jobs:
  build_packages:
    runs-on: windows-latest

    strategy:
      matrix:
        platform: ["win"]
        arch: ["x64"]

    steps:
      - name: Fetch code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fetching submodule tags and checkout specific version
        run: |
          git submodule foreach --recursive 'git fetch --tags'
          git submodule foreach --recursive '
            git checkout tags/4.11.0 || echo "Tag 4.11.0 not found in $name";
            git reset --hard tags/4.11.0 || echo "Reset failed for $name"'
      
      - name: Add MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Check CMake Version
        run: cmake --version
      
      - name: Add VCPKG via Source
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV
          echo "PATH=$PATH:$(pwd)/vcpkg" >> $GITHUB_ENV
