name: Windows Server 2022

on:
  pull_request:
    types: [synchronize, opened]
  push:

env:
  OPENCV_VERSION: 4.10.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2022"]
        arch: ["x86", "x64", "arm64"]

    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - uses: lukka/get-cmake@latest

      - name: Build and Install Dependencies with vcpkg
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: |
            opencv4[contrib]
          triplet: ${{ matrix.arch }}-windows-static
          cache-key: vcpkg-${{ matrix.arch }}-${{ matrix.os }}
          revision: master
          token: ${{ github.token }}
          github-binarycache: true

      - name: Configure Project with CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A ${{ matrix.arch }} \
            -DCMAKE_TOOLCHAIN_FILE=${{ steps.vcpkg.outputs.vcpkgRoot }}/scripts/buildsystems/vcpkg.cmake

      - name: Build Project with CMake
        run: |
          cd build
          cmake --build . --config Release
