name: Windows Server 2022

on:
  pull_request:
    types: [synchronize, opened]
  push:

env:
  OPENCV_VERSION: 4.10.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["win"]
        #platform: ["win", "uwp"]
        arch: ["x86", "x64", "ARM", "arm64"]
        exclude:
          - platform: win
            arch: ARM

    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

  #    - name: Install Server-Media-Foundation
  #      shell: powershell
  #      run: |
  #        Install-WindowsFeature Server-Media-Foundation

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

  #    - name: Install NASM to support SIMD optimizations
  #      uses: ilammy/setup-nasm@v1
      
      - uses: lukka/get-cmake@latest

      - name: Cache vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/vcpkg
            ${{ github.workspace }}/vcpkg/downloads
          key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      - name: Setup anew (or from cache) vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'

      - name: Cache CMake
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build
          key: cmake-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-${{ runner.os }}-

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake .. -A ${{ matrix.arch }} -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config Release
