name: Windows Server 2022

on:
  pull_request:
    types: [synchronize, opened]
  push:

env:
  OPENCV_VERSION: 4.10.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2022"]
        arch: ["x86", "x64", "arm64"]

    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - uses: lukka/get-cmake@latest

      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: |
            opencv4[contrib]
          triplet: ${{ matrix.arch }}-windows-static
          cache-key: vcpkg-${{ matrix.arch }}-${{ matrix.os }}
          revision: master
          token: ${{ github.token }}
          github-binarycache: true

      - name: Cache CMake
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build
          key: cmake-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            cmake-${{ runner.os }}-

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake .. -A ${{ matrix.arch }} -DCMAKE_TOOLCHAIN_FILE=${{ steps.vcpkg.outputs.vcpkgRoot }}/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config Release
